package tw.edu.ym.csis.metadb.model;

public class EnumType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENUMTYPE.VALUE
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENUMTYPE.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENUMTYPE.MEASUNITID
     *
     * @mbggenerated
     */
    private Long measunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENUMTYPE.DISPLAYORDER
     *
     * @mbggenerated
     */
    private Long displayorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENUMTYPE.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENUMTYPE.VALUE
     *
     * @return the value of ENUMTYPE.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENUMTYPE.VALUE
     *
     * @param value the value for ENUMTYPE.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENUMTYPE.ID
     *
     * @return the value of ENUMTYPE.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENUMTYPE.ID
     *
     * @param id the value for ENUMTYPE.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENUMTYPE.MEASUNITID
     *
     * @return the value of ENUMTYPE.MEASUNITID
     *
     * @mbggenerated
     */
    public Long getMeasunitid() {
        return measunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENUMTYPE.MEASUNITID
     *
     * @param measunitid the value for ENUMTYPE.MEASUNITID
     *
     * @mbggenerated
     */
    public void setMeasunitid(Long measunitid) {
        this.measunitid = measunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENUMTYPE.DISPLAYORDER
     *
     * @return the value of ENUMTYPE.DISPLAYORDER
     *
     * @mbggenerated
     */
    public Long getDisplayorder() {
        return displayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENUMTYPE.DISPLAYORDER
     *
     * @param displayorder the value for ENUMTYPE.DISPLAYORDER
     *
     * @mbggenerated
     */
    public void setDisplayorder(Long displayorder) {
        this.displayorder = displayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENUMTYPE.DESCRIPTION
     *
     * @return the value of ENUMTYPE.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENUMTYPE.DESCRIPTION
     *
     * @param description the value for ENUMTYPE.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}