package tw.edu.ym.csis.metadb.model;

public class FormGroups {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FORMGROUPS.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FORMGROUPS.LAYOUTSEQUENCE
     *
     * @mbggenerated
     */
    private Long layoutsequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FORMGROUPS.FORMVERSIONID
     *
     * @mbggenerated
     */
    private Long formversionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FORMGROUPS.CHILDFORMID
     *
     * @mbggenerated
     */
    private Long childformid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FORMGROUPS.ID
     *
     * @return the value of FORMGROUPS.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FORMGROUPS.ID
     *
     * @param id the value for FORMGROUPS.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FORMGROUPS.LAYOUTSEQUENCE
     *
     * @return the value of FORMGROUPS.LAYOUTSEQUENCE
     *
     * @mbggenerated
     */
    public Long getLayoutsequence() {
        return layoutsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FORMGROUPS.LAYOUTSEQUENCE
     *
     * @param layoutsequence the value for FORMGROUPS.LAYOUTSEQUENCE
     *
     * @mbggenerated
     */
    public void setLayoutsequence(Long layoutsequence) {
        this.layoutsequence = layoutsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FORMGROUPS.FORMVERSIONID
     *
     * @return the value of FORMGROUPS.FORMVERSIONID
     *
     * @mbggenerated
     */
    public Long getFormversionid() {
        return formversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FORMGROUPS.FORMVERSIONID
     *
     * @param formversionid the value for FORMGROUPS.FORMVERSIONID
     *
     * @mbggenerated
     */
    public void setFormversionid(Long formversionid) {
        this.formversionid = formversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FORMGROUPS.CHILDFORMID
     *
     * @return the value of FORMGROUPS.CHILDFORMID
     *
     * @mbggenerated
     */
    public Long getChildformid() {
        return childformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FORMGROUPS.CHILDFORMID
     *
     * @param childformid the value for FORMGROUPS.CHILDFORMID
     *
     * @mbggenerated
     */
    public void setChildformid(Long childformid) {
        this.childformid = childformid;
    }
}