package tw.edu.ym.csis.metadb.model;

public class LabelLayout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABELLAYOUT.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABELLAYOUT.ROWNUMBER
     *
     * @mbggenerated
     */
    private Short rownumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABELLAYOUT.COLNUMBER
     *
     * @mbggenerated
     */
    private Short colnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABELLAYOUT.CELLTEXT
     *
     * @mbggenerated
     */
    private String celltext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABELLAYOUT.SECTIONID
     *
     * @mbggenerated
     */
    private Long sectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABELLAYOUT.WIDTH
     *
     * @mbggenerated
     */
    private Long width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABELLAYOUT.ALIGNMENT
     *
     * @mbggenerated
     */
    private String alignment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABELLAYOUT.ID
     *
     * @return the value of LABELLAYOUT.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABELLAYOUT.ID
     *
     * @param id the value for LABELLAYOUT.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABELLAYOUT.ROWNUMBER
     *
     * @return the value of LABELLAYOUT.ROWNUMBER
     *
     * @mbggenerated
     */
    public Short getRownumber() {
        return rownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABELLAYOUT.ROWNUMBER
     *
     * @param rownumber the value for LABELLAYOUT.ROWNUMBER
     *
     * @mbggenerated
     */
    public void setRownumber(Short rownumber) {
        this.rownumber = rownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABELLAYOUT.COLNUMBER
     *
     * @return the value of LABELLAYOUT.COLNUMBER
     *
     * @mbggenerated
     */
    public Short getColnumber() {
        return colnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABELLAYOUT.COLNUMBER
     *
     * @param colnumber the value for LABELLAYOUT.COLNUMBER
     *
     * @mbggenerated
     */
    public void setColnumber(Short colnumber) {
        this.colnumber = colnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABELLAYOUT.CELLTEXT
     *
     * @return the value of LABELLAYOUT.CELLTEXT
     *
     * @mbggenerated
     */
    public String getCelltext() {
        return celltext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABELLAYOUT.CELLTEXT
     *
     * @param celltext the value for LABELLAYOUT.CELLTEXT
     *
     * @mbggenerated
     */
    public void setCelltext(String celltext) {
        this.celltext = celltext == null ? null : celltext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABELLAYOUT.SECTIONID
     *
     * @return the value of LABELLAYOUT.SECTIONID
     *
     * @mbggenerated
     */
    public Long getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABELLAYOUT.SECTIONID
     *
     * @param sectionid the value for LABELLAYOUT.SECTIONID
     *
     * @mbggenerated
     */
    public void setSectionid(Long sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABELLAYOUT.WIDTH
     *
     * @return the value of LABELLAYOUT.WIDTH
     *
     * @mbggenerated
     */
    public Long getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABELLAYOUT.WIDTH
     *
     * @param width the value for LABELLAYOUT.WIDTH
     *
     * @mbggenerated
     */
    public void setWidth(Long width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABELLAYOUT.ALIGNMENT
     *
     * @return the value of LABELLAYOUT.ALIGNMENT
     *
     * @mbggenerated
     */
    public String getAlignment() {
        return alignment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABELLAYOUT.ALIGNMENT
     *
     * @param alignment the value for LABELLAYOUT.ALIGNMENT
     *
     * @mbggenerated
     */
    public void setAlignment(String alignment) {
        this.alignment = alignment == null ? null : alignment.trim();
    }
}