package tw.edu.ym.csis.metadb.model;

import java.util.ArrayList;
import java.util.List;

public class QuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public QuestionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSectionidIsNull() {
            addCriterion("SECTIONID is null");
            return (Criteria) this;
        }

        public Criteria andSectionidIsNotNull() {
            addCriterion("SECTIONID is not null");
            return (Criteria) this;
        }

        public Criteria andSectionidEqualTo(Long value) {
            addCriterion("SECTIONID =", value, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidNotEqualTo(Long value) {
            addCriterion("SECTIONID <>", value, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidGreaterThan(Long value) {
            addCriterion("SECTIONID >", value, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidGreaterThanOrEqualTo(Long value) {
            addCriterion("SECTIONID >=", value, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidLessThan(Long value) {
            addCriterion("SECTIONID <", value, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidLessThanOrEqualTo(Long value) {
            addCriterion("SECTIONID <=", value, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidIn(List<Long> values) {
            addCriterion("SECTIONID in", values, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidNotIn(List<Long> values) {
            addCriterion("SECTIONID not in", values, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidBetween(Long value1, Long value2) {
            addCriterion("SECTIONID between", value1, value2, "sectionid");
            return (Criteria) this;
        }

        public Criteria andSectionidNotBetween(Long value1, Long value2) {
            addCriterion("SECTIONID not between", value1, value2, "sectionid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridIsNull() {
            addCriterion("PREFILLATTRID is null");
            return (Criteria) this;
        }

        public Criteria andPrefillattridIsNotNull() {
            addCriterion("PREFILLATTRID is not null");
            return (Criteria) this;
        }

        public Criteria andPrefillattridEqualTo(Long value) {
            addCriterion("PREFILLATTRID =", value, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridNotEqualTo(Long value) {
            addCriterion("PREFILLATTRID <>", value, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridGreaterThan(Long value) {
            addCriterion("PREFILLATTRID >", value, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridGreaterThanOrEqualTo(Long value) {
            addCriterion("PREFILLATTRID >=", value, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridLessThan(Long value) {
            addCriterion("PREFILLATTRID <", value, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridLessThanOrEqualTo(Long value) {
            addCriterion("PREFILLATTRID <=", value, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridIn(List<Long> values) {
            addCriterion("PREFILLATTRID in", values, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridNotIn(List<Long> values) {
            addCriterion("PREFILLATTRID not in", values, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridBetween(Long value1, Long value2) {
            addCriterion("PREFILLATTRID between", value1, value2, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andPrefillattridNotBetween(Long value1, Long value2) {
            addCriterion("PREFILLATTRID not between", value1, value2, "prefillattrid");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceIsNull() {
            addCriterion("QUESTIONSEQUENCE is null");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceIsNotNull() {
            addCriterion("QUESTIONSEQUENCE is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceEqualTo(Long value) {
            addCriterion("QUESTIONSEQUENCE =", value, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceNotEqualTo(Long value) {
            addCriterion("QUESTIONSEQUENCE <>", value, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceGreaterThan(Long value) {
            addCriterion("QUESTIONSEQUENCE >", value, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceGreaterThanOrEqualTo(Long value) {
            addCriterion("QUESTIONSEQUENCE >=", value, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceLessThan(Long value) {
            addCriterion("QUESTIONSEQUENCE <", value, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceLessThanOrEqualTo(Long value) {
            addCriterion("QUESTIONSEQUENCE <=", value, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceIn(List<Long> values) {
            addCriterion("QUESTIONSEQUENCE in", values, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceNotIn(List<Long> values) {
            addCriterion("QUESTIONSEQUENCE not in", values, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceBetween(Long value1, Long value2) {
            addCriterion("QUESTIONSEQUENCE between", value1, value2, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andQuestionsequenceNotBetween(Long value1, Long value2) {
            addCriterion("QUESTIONSEQUENCE not between", value1, value2, "questionsequence");
            return (Criteria) this;
        }

        public Criteria andDatapointidIsNull() {
            addCriterion("DATAPOINTID is null");
            return (Criteria) this;
        }

        public Criteria andDatapointidIsNotNull() {
            addCriterion("DATAPOINTID is not null");
            return (Criteria) this;
        }

        public Criteria andDatapointidEqualTo(Long value) {
            addCriterion("DATAPOINTID =", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidNotEqualTo(Long value) {
            addCriterion("DATAPOINTID <>", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidGreaterThan(Long value) {
            addCriterion("DATAPOINTID >", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidGreaterThanOrEqualTo(Long value) {
            addCriterion("DATAPOINTID >=", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidLessThan(Long value) {
            addCriterion("DATAPOINTID <", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidLessThanOrEqualTo(Long value) {
            addCriterion("DATAPOINTID <=", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidIn(List<Long> values) {
            addCriterion("DATAPOINTID in", values, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidNotIn(List<Long> values) {
            addCriterion("DATAPOINTID not in", values, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidBetween(Long value1, Long value2) {
            addCriterion("DATAPOINTID between", value1, value2, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidNotBetween(Long value1, Long value2) {
            addCriterion("DATAPOINTID not between", value1, value2, "datapointid");
            return (Criteria) this;
        }

        public Criteria andQuestiontextIsNull() {
            addCriterion("QUESTIONTEXT is null");
            return (Criteria) this;
        }

        public Criteria andQuestiontextIsNotNull() {
            addCriterion("QUESTIONTEXT is not null");
            return (Criteria) this;
        }

        public Criteria andQuestiontextEqualTo(String value) {
            addCriterion("QUESTIONTEXT =", value, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextNotEqualTo(String value) {
            addCriterion("QUESTIONTEXT <>", value, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextGreaterThan(String value) {
            addCriterion("QUESTIONTEXT >", value, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTIONTEXT >=", value, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextLessThan(String value) {
            addCriterion("QUESTIONTEXT <", value, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextLessThanOrEqualTo(String value) {
            addCriterion("QUESTIONTEXT <=", value, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextLike(String value) {
            addCriterion("QUESTIONTEXT like", value, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextNotLike(String value) {
            addCriterion("QUESTIONTEXT not like", value, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextIn(List<String> values) {
            addCriterion("QUESTIONTEXT in", values, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextNotIn(List<String> values) {
            addCriterion("QUESTIONTEXT not in", values, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextBetween(String value1, String value2) {
            addCriterion("QUESTIONTEXT between", value1, value2, "questiontext");
            return (Criteria) this;
        }

        public Criteria andQuestiontextNotBetween(String value1, String value2) {
            addCriterion("QUESTIONTEXT not between", value1, value2, "questiontext");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgIsNull() {
            addCriterion("PREFILLREADONLY_FLG is null");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgIsNotNull() {
            addCriterion("PREFILLREADONLY_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgEqualTo(String value) {
            addCriterion("PREFILLREADONLY_FLG =", value, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgNotEqualTo(String value) {
            addCriterion("PREFILLREADONLY_FLG <>", value, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgGreaterThan(String value) {
            addCriterion("PREFILLREADONLY_FLG >", value, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgGreaterThanOrEqualTo(String value) {
            addCriterion("PREFILLREADONLY_FLG >=", value, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgLessThan(String value) {
            addCriterion("PREFILLREADONLY_FLG <", value, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgLessThanOrEqualTo(String value) {
            addCriterion("PREFILLREADONLY_FLG <=", value, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgLike(String value) {
            addCriterion("PREFILLREADONLY_FLG like", value, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgNotLike(String value) {
            addCriterion("PREFILLREADONLY_FLG not like", value, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgIn(List<String> values) {
            addCriterion("PREFILLREADONLY_FLG in", values, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgNotIn(List<String> values) {
            addCriterion("PREFILLREADONLY_FLG not in", values, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgBetween(String value1, String value2) {
            addCriterion("PREFILLREADONLY_FLG between", value1, value2, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andPrefillreadonlyFlgNotBetween(String value1, String value2) {
            addCriterion("PREFILLREADONLY_FLG not between", value1, value2, "prefillreadonlyFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgIsNull() {
            addCriterion("REQUIRED_FLG is null");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgIsNotNull() {
            addCriterion("REQUIRED_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgEqualTo(String value) {
            addCriterion("REQUIRED_FLG =", value, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgNotEqualTo(String value) {
            addCriterion("REQUIRED_FLG <>", value, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgGreaterThan(String value) {
            addCriterion("REQUIRED_FLG >", value, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgGreaterThanOrEqualTo(String value) {
            addCriterion("REQUIRED_FLG >=", value, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgLessThan(String value) {
            addCriterion("REQUIRED_FLG <", value, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgLessThanOrEqualTo(String value) {
            addCriterion("REQUIRED_FLG <=", value, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgLike(String value) {
            addCriterion("REQUIRED_FLG like", value, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgNotLike(String value) {
            addCriterion("REQUIRED_FLG not like", value, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgIn(List<String> values) {
            addCriterion("REQUIRED_FLG in", values, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgNotIn(List<String> values) {
            addCriterion("REQUIRED_FLG not in", values, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgBetween(String value1, String value2) {
            addCriterion("REQUIRED_FLG between", value1, value2, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andRequiredFlgNotBetween(String value1, String value2) {
            addCriterion("REQUIRED_FLG not between", value1, value2, "requiredFlg");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIsNull() {
            addCriterion("DEFAULTVALUE is null");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIsNotNull() {
            addCriterion("DEFAULTVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueEqualTo(String value) {
            addCriterion("DEFAULTVALUE =", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotEqualTo(String value) {
            addCriterion("DEFAULTVALUE <>", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueGreaterThan(String value) {
            addCriterion("DEFAULTVALUE >", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueGreaterThanOrEqualTo(String value) {
            addCriterion("DEFAULTVALUE >=", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLessThan(String value) {
            addCriterion("DEFAULTVALUE <", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLessThanOrEqualTo(String value) {
            addCriterion("DEFAULTVALUE <=", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLike(String value) {
            addCriterion("DEFAULTVALUE like", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotLike(String value) {
            addCriterion("DEFAULTVALUE not like", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIn(List<String> values) {
            addCriterion("DEFAULTVALUE in", values, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotIn(List<String> values) {
            addCriterion("DEFAULTVALUE not in", values, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueBetween(String value1, String value2) {
            addCriterion("DEFAULTVALUE between", value1, value2, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotBetween(String value1, String value2) {
            addCriterion("DEFAULTVALUE not between", value1, value2, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andFgcolorIsNull() {
            addCriterion("FGCOLOR is null");
            return (Criteria) this;
        }

        public Criteria andFgcolorIsNotNull() {
            addCriterion("FGCOLOR is not null");
            return (Criteria) this;
        }

        public Criteria andFgcolorEqualTo(String value) {
            addCriterion("FGCOLOR =", value, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorNotEqualTo(String value) {
            addCriterion("FGCOLOR <>", value, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorGreaterThan(String value) {
            addCriterion("FGCOLOR >", value, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorGreaterThanOrEqualTo(String value) {
            addCriterion("FGCOLOR >=", value, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorLessThan(String value) {
            addCriterion("FGCOLOR <", value, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorLessThanOrEqualTo(String value) {
            addCriterion("FGCOLOR <=", value, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorLike(String value) {
            addCriterion("FGCOLOR like", value, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorNotLike(String value) {
            addCriterion("FGCOLOR not like", value, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorIn(List<String> values) {
            addCriterion("FGCOLOR in", values, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorNotIn(List<String> values) {
            addCriterion("FGCOLOR not in", values, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorBetween(String value1, String value2) {
            addCriterion("FGCOLOR between", value1, value2, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andFgcolorNotBetween(String value1, String value2) {
            addCriterion("FGCOLOR not between", value1, value2, "fgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorIsNull() {
            addCriterion("BGCOLOR is null");
            return (Criteria) this;
        }

        public Criteria andBgcolorIsNotNull() {
            addCriterion("BGCOLOR is not null");
            return (Criteria) this;
        }

        public Criteria andBgcolorEqualTo(String value) {
            addCriterion("BGCOLOR =", value, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorNotEqualTo(String value) {
            addCriterion("BGCOLOR <>", value, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorGreaterThan(String value) {
            addCriterion("BGCOLOR >", value, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorGreaterThanOrEqualTo(String value) {
            addCriterion("BGCOLOR >=", value, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorLessThan(String value) {
            addCriterion("BGCOLOR <", value, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorLessThanOrEqualTo(String value) {
            addCriterion("BGCOLOR <=", value, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorLike(String value) {
            addCriterion("BGCOLOR like", value, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorNotLike(String value) {
            addCriterion("BGCOLOR not like", value, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorIn(List<String> values) {
            addCriterion("BGCOLOR in", values, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorNotIn(List<String> values) {
            addCriterion("BGCOLOR not in", values, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorBetween(String value1, String value2) {
            addCriterion("BGCOLOR between", value1, value2, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andBgcolorNotBetween(String value1, String value2) {
            addCriterion("BGCOLOR not between", value1, value2, "bgcolor");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("WIDTH is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("WIDTH is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Long value) {
            addCriterion("WIDTH =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Long value) {
            addCriterion("WIDTH <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Long value) {
            addCriterion("WIDTH >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Long value) {
            addCriterion("WIDTH >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Long value) {
            addCriterion("WIDTH <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Long value) {
            addCriterion("WIDTH <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Long> values) {
            addCriterion("WIDTH in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Long> values) {
            addCriterion("WIDTH not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Long value1, Long value2) {
            addCriterion("WIDTH between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Long value1, Long value2) {
            addCriterion("WIDTH not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgIsNull() {
            addCriterion("CALCULATE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgIsNotNull() {
            addCriterion("CALCULATE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgEqualTo(String value) {
            addCriterion("CALCULATE_FLG =", value, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgNotEqualTo(String value) {
            addCriterion("CALCULATE_FLG <>", value, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgGreaterThan(String value) {
            addCriterion("CALCULATE_FLG >", value, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgGreaterThanOrEqualTo(String value) {
            addCriterion("CALCULATE_FLG >=", value, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgLessThan(String value) {
            addCriterion("CALCULATE_FLG <", value, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgLessThanOrEqualTo(String value) {
            addCriterion("CALCULATE_FLG <=", value, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgLike(String value) {
            addCriterion("CALCULATE_FLG like", value, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgNotLike(String value) {
            addCriterion("CALCULATE_FLG not like", value, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgIn(List<String> values) {
            addCriterion("CALCULATE_FLG in", values, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgNotIn(List<String> values) {
            addCriterion("CALCULATE_FLG not in", values, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgBetween(String value1, String value2) {
            addCriterion("CALCULATE_FLG between", value1, value2, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andCalculateFlgNotBetween(String value1, String value2) {
            addCriterion("CALCULATE_FLG not between", value1, value2, "calculateFlg");
            return (Criteria) this;
        }

        public Criteria andImageidIsNull() {
            addCriterion("IMAGEID is null");
            return (Criteria) this;
        }

        public Criteria andImageidIsNotNull() {
            addCriterion("IMAGEID is not null");
            return (Criteria) this;
        }

        public Criteria andImageidEqualTo(Long value) {
            addCriterion("IMAGEID =", value, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidNotEqualTo(Long value) {
            addCriterion("IMAGEID <>", value, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidGreaterThan(Long value) {
            addCriterion("IMAGEID >", value, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidGreaterThanOrEqualTo(Long value) {
            addCriterion("IMAGEID >=", value, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidLessThan(Long value) {
            addCriterion("IMAGEID <", value, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidLessThanOrEqualTo(Long value) {
            addCriterion("IMAGEID <=", value, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidIn(List<Long> values) {
            addCriterion("IMAGEID in", values, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidNotIn(List<Long> values) {
            addCriterion("IMAGEID not in", values, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidBetween(Long value1, Long value2) {
            addCriterion("IMAGEID between", value1, value2, "imageid");
            return (Criteria) this;
        }

        public Criteria andImageidNotBetween(Long value1, Long value2) {
            addCriterion("IMAGEID not between", value1, value2, "imageid");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgIsNull() {
            addCriterion("VISIBLE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgIsNotNull() {
            addCriterion("VISIBLE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgEqualTo(String value) {
            addCriterion("VISIBLE_FLG =", value, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgNotEqualTo(String value) {
            addCriterion("VISIBLE_FLG <>", value, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgGreaterThan(String value) {
            addCriterion("VISIBLE_FLG >", value, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgGreaterThanOrEqualTo(String value) {
            addCriterion("VISIBLE_FLG >=", value, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgLessThan(String value) {
            addCriterion("VISIBLE_FLG <", value, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgLessThanOrEqualTo(String value) {
            addCriterion("VISIBLE_FLG <=", value, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgLike(String value) {
            addCriterion("VISIBLE_FLG like", value, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgNotLike(String value) {
            addCriterion("VISIBLE_FLG not like", value, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgIn(List<String> values) {
            addCriterion("VISIBLE_FLG in", values, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgNotIn(List<String> values) {
            addCriterion("VISIBLE_FLG not in", values, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgBetween(String value1, String value2) {
            addCriterion("VISIBLE_FLG between", value1, value2, "visibleFlg");
            return (Criteria) this;
        }

        public Criteria andVisibleFlgNotBetween(String value1, String value2) {
            addCriterion("VISIBLE_FLG not between", value1, value2, "visibleFlg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUESTION
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUESTION
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}