package tw.edu.ym.csis.metadb.model;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.SECTIONID
     *
     * @mbggenerated
     */
    private Long sectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.PREFILLATTRID
     *
     * @mbggenerated
     */
    private Long prefillattrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.QUESTIONSEQUENCE
     *
     * @mbggenerated
     */
    private Long questionsequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.DATAPOINTID
     *
     * @mbggenerated
     */
    private Long datapointid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.QUESTIONTEXT
     *
     * @mbggenerated
     */
    private String questiontext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.PREFILLREADONLY_FLG
     *
     * @mbggenerated
     */
    private String prefillreadonlyFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.REQUIRED_FLG
     *
     * @mbggenerated
     */
    private String requiredFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.DEFAULTVALUE
     *
     * @mbggenerated
     */
    private String defaultvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.FGCOLOR
     *
     * @mbggenerated
     */
    private String fgcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.BGCOLOR
     *
     * @mbggenerated
     */
    private String bgcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.WIDTH
     *
     * @mbggenerated
     */
    private Long width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.CALCULATE_FLG
     *
     * @mbggenerated
     */
    private String calculateFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.IMAGEID
     *
     * @mbggenerated
     */
    private Long imageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.VISIBLE_FLG
     *
     * @mbggenerated
     */
    private String visibleFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.ID
     *
     * @return the value of QUESTION.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.ID
     *
     * @param id the value for QUESTION.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.SECTIONID
     *
     * @return the value of QUESTION.SECTIONID
     *
     * @mbggenerated
     */
    public Long getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.SECTIONID
     *
     * @param sectionid the value for QUESTION.SECTIONID
     *
     * @mbggenerated
     */
    public void setSectionid(Long sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.PREFILLATTRID
     *
     * @return the value of QUESTION.PREFILLATTRID
     *
     * @mbggenerated
     */
    public Long getPrefillattrid() {
        return prefillattrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.PREFILLATTRID
     *
     * @param prefillattrid the value for QUESTION.PREFILLATTRID
     *
     * @mbggenerated
     */
    public void setPrefillattrid(Long prefillattrid) {
        this.prefillattrid = prefillattrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.QUESTIONSEQUENCE
     *
     * @return the value of QUESTION.QUESTIONSEQUENCE
     *
     * @mbggenerated
     */
    public Long getQuestionsequence() {
        return questionsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.QUESTIONSEQUENCE
     *
     * @param questionsequence the value for QUESTION.QUESTIONSEQUENCE
     *
     * @mbggenerated
     */
    public void setQuestionsequence(Long questionsequence) {
        this.questionsequence = questionsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.DATAPOINTID
     *
     * @return the value of QUESTION.DATAPOINTID
     *
     * @mbggenerated
     */
    public Long getDatapointid() {
        return datapointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.DATAPOINTID
     *
     * @param datapointid the value for QUESTION.DATAPOINTID
     *
     * @mbggenerated
     */
    public void setDatapointid(Long datapointid) {
        this.datapointid = datapointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.QUESTIONTEXT
     *
     * @return the value of QUESTION.QUESTIONTEXT
     *
     * @mbggenerated
     */
    public String getQuestiontext() {
        return questiontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.QUESTIONTEXT
     *
     * @param questiontext the value for QUESTION.QUESTIONTEXT
     *
     * @mbggenerated
     */
    public void setQuestiontext(String questiontext) {
        this.questiontext = questiontext == null ? null : questiontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.PREFILLREADONLY_FLG
     *
     * @return the value of QUESTION.PREFILLREADONLY_FLG
     *
     * @mbggenerated
     */
    public String getPrefillreadonlyFlg() {
        return prefillreadonlyFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.PREFILLREADONLY_FLG
     *
     * @param prefillreadonlyFlg the value for QUESTION.PREFILLREADONLY_FLG
     *
     * @mbggenerated
     */
    public void setPrefillreadonlyFlg(String prefillreadonlyFlg) {
        this.prefillreadonlyFlg = prefillreadonlyFlg == null ? null : prefillreadonlyFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.REQUIRED_FLG
     *
     * @return the value of QUESTION.REQUIRED_FLG
     *
     * @mbggenerated
     */
    public String getRequiredFlg() {
        return requiredFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.REQUIRED_FLG
     *
     * @param requiredFlg the value for QUESTION.REQUIRED_FLG
     *
     * @mbggenerated
     */
    public void setRequiredFlg(String requiredFlg) {
        this.requiredFlg = requiredFlg == null ? null : requiredFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.DEFAULTVALUE
     *
     * @return the value of QUESTION.DEFAULTVALUE
     *
     * @mbggenerated
     */
    public String getDefaultvalue() {
        return defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.DEFAULTVALUE
     *
     * @param defaultvalue the value for QUESTION.DEFAULTVALUE
     *
     * @mbggenerated
     */
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue == null ? null : defaultvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.FGCOLOR
     *
     * @return the value of QUESTION.FGCOLOR
     *
     * @mbggenerated
     */
    public String getFgcolor() {
        return fgcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.FGCOLOR
     *
     * @param fgcolor the value for QUESTION.FGCOLOR
     *
     * @mbggenerated
     */
    public void setFgcolor(String fgcolor) {
        this.fgcolor = fgcolor == null ? null : fgcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.BGCOLOR
     *
     * @return the value of QUESTION.BGCOLOR
     *
     * @mbggenerated
     */
    public String getBgcolor() {
        return bgcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.BGCOLOR
     *
     * @param bgcolor the value for QUESTION.BGCOLOR
     *
     * @mbggenerated
     */
    public void setBgcolor(String bgcolor) {
        this.bgcolor = bgcolor == null ? null : bgcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.WIDTH
     *
     * @return the value of QUESTION.WIDTH
     *
     * @mbggenerated
     */
    public Long getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.WIDTH
     *
     * @param width the value for QUESTION.WIDTH
     *
     * @mbggenerated
     */
    public void setWidth(Long width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.CALCULATE_FLG
     *
     * @return the value of QUESTION.CALCULATE_FLG
     *
     * @mbggenerated
     */
    public String getCalculateFlg() {
        return calculateFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.CALCULATE_FLG
     *
     * @param calculateFlg the value for QUESTION.CALCULATE_FLG
     *
     * @mbggenerated
     */
    public void setCalculateFlg(String calculateFlg) {
        this.calculateFlg = calculateFlg == null ? null : calculateFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.IMAGEID
     *
     * @return the value of QUESTION.IMAGEID
     *
     * @mbggenerated
     */
    public Long getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.IMAGEID
     *
     * @param imageid the value for QUESTION.IMAGEID
     *
     * @mbggenerated
     */
    public void setImageid(Long imageid) {
        this.imageid = imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.VISIBLE_FLG
     *
     * @return the value of QUESTION.VISIBLE_FLG
     *
     * @mbggenerated
     */
    public String getVisibleFlg() {
        return visibleFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.VISIBLE_FLG
     *
     * @param visibleFlg the value for QUESTION.VISIBLE_FLG
     *
     * @mbggenerated
     */
    public void setVisibleFlg(String visibleFlg) {
        this.visibleFlg = visibleFlg == null ? null : visibleFlg.trim();
    }
}