package tw.edu.ym.csis.metadb.model;

import java.math.BigDecimal;
import java.util.Date;

public class SkippingRuleDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.SKIPPINGRULEID
     *
     * @mbggenerated
     */
    private BigDecimal skippingruleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.SRCQUESTIONID
     *
     * @mbggenerated
     */
    private BigDecimal srcquestionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.TRGQUESTIONID
     *
     * @mbggenerated
     */
    private BigDecimal trgquestionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.CREATEDDATE
     *
     * @mbggenerated
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.CREATORID
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.LASTUPDDATE
     *
     * @mbggenerated
     */
    private Date lastupddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.LASTUPDID
     *
     * @mbggenerated
     */
    private String lastupdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKIPRULEDETAIL.ACTION
     *
     * @mbggenerated
     */
    private String action;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.ID
     *
     * @return the value of SKIPRULEDETAIL.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.ID
     *
     * @param id the value for SKIPRULEDETAIL.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.SKIPPINGRULEID
     *
     * @return the value of SKIPRULEDETAIL.SKIPPINGRULEID
     *
     * @mbggenerated
     */
    public BigDecimal getSkippingruleid() {
        return skippingruleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.SKIPPINGRULEID
     *
     * @param skippingruleid the value for SKIPRULEDETAIL.SKIPPINGRULEID
     *
     * @mbggenerated
     */
    public void setSkippingruleid(BigDecimal skippingruleid) {
        this.skippingruleid = skippingruleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.SRCQUESTIONID
     *
     * @return the value of SKIPRULEDETAIL.SRCQUESTIONID
     *
     * @mbggenerated
     */
    public BigDecimal getSrcquestionid() {
        return srcquestionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.SRCQUESTIONID
     *
     * @param srcquestionid the value for SKIPRULEDETAIL.SRCQUESTIONID
     *
     * @mbggenerated
     */
    public void setSrcquestionid(BigDecimal srcquestionid) {
        this.srcquestionid = srcquestionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.TRGQUESTIONID
     *
     * @return the value of SKIPRULEDETAIL.TRGQUESTIONID
     *
     * @mbggenerated
     */
    public BigDecimal getTrgquestionid() {
        return trgquestionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.TRGQUESTIONID
     *
     * @param trgquestionid the value for SKIPRULEDETAIL.TRGQUESTIONID
     *
     * @mbggenerated
     */
    public void setTrgquestionid(BigDecimal trgquestionid) {
        this.trgquestionid = trgquestionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.CREATEDDATE
     *
     * @return the value of SKIPRULEDETAIL.CREATEDDATE
     *
     * @mbggenerated
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.CREATEDDATE
     *
     * @param createddate the value for SKIPRULEDETAIL.CREATEDDATE
     *
     * @mbggenerated
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.CREATORID
     *
     * @return the value of SKIPRULEDETAIL.CREATORID
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.CREATORID
     *
     * @param creatorid the value for SKIPRULEDETAIL.CREATORID
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.LASTUPDDATE
     *
     * @return the value of SKIPRULEDETAIL.LASTUPDDATE
     *
     * @mbggenerated
     */
    public Date getLastupddate() {
        return lastupddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.LASTUPDDATE
     *
     * @param lastupddate the value for SKIPRULEDETAIL.LASTUPDDATE
     *
     * @mbggenerated
     */
    public void setLastupddate(Date lastupddate) {
        this.lastupddate = lastupddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.LASTUPDID
     *
     * @return the value of SKIPRULEDETAIL.LASTUPDID
     *
     * @mbggenerated
     */
    public String getLastupdid() {
        return lastupdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.LASTUPDID
     *
     * @param lastupdid the value for SKIPRULEDETAIL.LASTUPDID
     *
     * @mbggenerated
     */
    public void setLastupdid(String lastupdid) {
        this.lastupdid = lastupdid == null ? null : lastupdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKIPRULEDETAIL.ACTION
     *
     * @return the value of SKIPRULEDETAIL.ACTION
     *
     * @mbggenerated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKIPRULEDETAIL.ACTION
     *
     * @param action the value for SKIPRULEDETAIL.ACTION
     *
     * @mbggenerated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }
}