package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.Attachment;
import tw.edu.ym.csis.maindb.model.AttachmentExample;

public interface AttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated
     */
    int countByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated
     */
    int deleteByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated
     */
    List<Attachment> selectByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Attachment record, @Param("example") AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACHMENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Attachment record, @Param("example") AttachmentExample example);
}