package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.ClobContent;
import tw.edu.ym.csis.maindb.model.ClobContentExample;

public interface ClobContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    int countByExample(ClobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    int deleteByExample(ClobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    int insert(ClobContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    int insertSelective(ClobContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    List<ClobContent> selectByExampleWithBLOBs(ClobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    List<ClobContent> selectByExample(ClobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClobContent record, @Param("example") ClobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ClobContent record, @Param("example") ClobContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLOBCONTENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClobContent record, @Param("example") ClobContentExample example);
}