package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.ComparisionCriterion;
import tw.edu.ym.csis.maindb.model.ComparisionCriterionExample;

public interface ComparisionCriterionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPARISONCRITERION
     *
     * @mbggenerated
     */
    int countByExample(ComparisionCriterionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPARISONCRITERION
     *
     * @mbggenerated
     */
    int deleteByExample(ComparisionCriterionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPARISONCRITERION
     *
     * @mbggenerated
     */
    int insert(ComparisionCriterion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPARISONCRITERION
     *
     * @mbggenerated
     */
    int insertSelective(ComparisionCriterion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPARISONCRITERION
     *
     * @mbggenerated
     */
    List<ComparisionCriterion> selectByExample(ComparisionCriterionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPARISONCRITERION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ComparisionCriterion record, @Param("example") ComparisionCriterionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMPARISONCRITERION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ComparisionCriterion record, @Param("example") ComparisionCriterionExample example);
}