package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.Datarecord;
import tw.edu.ym.csis.maindb.model.DatarecordExample;

public interface DatarecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATARECORD
     *
     * @mbggenerated
     */
    int countByExample(DatarecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATARECORD
     *
     * @mbggenerated
     */
    int deleteByExample(DatarecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATARECORD
     *
     * @mbggenerated
     */
    int insert(Datarecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATARECORD
     *
     * @mbggenerated
     */
    int insertSelective(Datarecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATARECORD
     *
     * @mbggenerated
     */
    List<Datarecord> selectByExample(DatarecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATARECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Datarecord record, @Param("example") DatarecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATARECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Datarecord record, @Param("example") DatarecordExample example);
}