package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.EventHistory;
import tw.edu.ym.csis.maindb.model.EventHistoryExample;

public interface EventHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(EventHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(EventHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_HISTORY
     *
     * @mbggenerated
     */
    int insert(EventHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(EventHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_HISTORY
     *
     * @mbggenerated
     */
    List<EventHistory> selectByExample(EventHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EventHistory record, @Param("example") EventHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EventHistory record, @Param("example") EventHistoryExample example);
}