package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.ImageData;
import tw.edu.ym.csis.maindb.model.ImageDataExample;

public interface ImageDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int countByExample(ImageDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int deleteByExample(ImageDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int insert(ImageData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int insertSelective(ImageData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    List<ImageData> selectByExample(ImageDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    ImageData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ImageData record, @Param("example") ImageDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ImageData record, @Param("example") ImageDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImageData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGEDATA
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImageData record);
}