package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.Patient;
import tw.edu.ym.csis.maindb.model.PatientExample;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    int countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    int deleteByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    List<Patient> selectByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Patient record, @Param("example") PatientExample example);
}