package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.PatientDiagnosis;
import tw.edu.ym.csis.maindb.model.PatientDiagnosisExample;

public interface PatientDiagnosisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    int countByExample(PatientDiagnosisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    int deleteByExample(PatientDiagnosisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    int insert(PatientDiagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    int insertSelective(PatientDiagnosis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    List<PatientDiagnosis> selectByExampleWithBLOBs(PatientDiagnosisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    List<PatientDiagnosis> selectByExample(PatientDiagnosisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PatientDiagnosis record, @Param("example") PatientDiagnosisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") PatientDiagnosis record, @Param("example") PatientDiagnosisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTDIAGNOSIS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PatientDiagnosis record, @Param("example") PatientDiagnosisExample example);
}