package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.PatientRecruitAction;
import tw.edu.ym.csis.maindb.model.PatientRecruitActionExample;

public interface PatientRecruitActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTRECRUITACTION
     *
     * @mbggenerated
     */
    int countByExample(PatientRecruitActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTRECRUITACTION
     *
     * @mbggenerated
     */
    int deleteByExample(PatientRecruitActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTRECRUITACTION
     *
     * @mbggenerated
     */
    int insert(PatientRecruitAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTRECRUITACTION
     *
     * @mbggenerated
     */
    int insertSelective(PatientRecruitAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTRECRUITACTION
     *
     * @mbggenerated
     */
    List<PatientRecruitAction> selectByExample(PatientRecruitActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTRECRUITACTION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PatientRecruitAction record, @Param("example") PatientRecruitActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENTRECRUITACTION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PatientRecruitAction record, @Param("example") PatientRecruitActionExample example);
}