package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.Report;
import tw.edu.ym.csis.maindb.model.ReportExample;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbggenerated
     */
    int countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbggenerated
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbggenerated
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbggenerated
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbggenerated
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);
}