package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.SavedQuery;
import tw.edu.ym.csis.maindb.model.SavedQueryExample;

public interface SavedQueryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAVEDQUERY
     *
     * @mbggenerated
     */
    int countByExample(SavedQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAVEDQUERY
     *
     * @mbggenerated
     */
    int deleteByExample(SavedQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAVEDQUERY
     *
     * @mbggenerated
     */
    int insert(SavedQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAVEDQUERY
     *
     * @mbggenerated
     */
    int insertSelective(SavedQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAVEDQUERY
     *
     * @mbggenerated
     */
    List<SavedQuery> selectByExample(SavedQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAVEDQUERY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SavedQuery record, @Param("example") SavedQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SAVEDQUERY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SavedQuery record, @Param("example") SavedQueryExample example);
}