package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.SchemaMeta;
import tw.edu.ym.csis.maindb.model.SchemaMetaExample;

public interface SchemaMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMAMETA
     *
     * @mbggenerated
     */
    int countByExample(SchemaMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMAMETA
     *
     * @mbggenerated
     */
    int deleteByExample(SchemaMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMAMETA
     *
     * @mbggenerated
     */
    int insert(SchemaMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMAMETA
     *
     * @mbggenerated
     */
    int insertSelective(SchemaMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMAMETA
     *
     * @mbggenerated
     */
    List<SchemaMeta> selectByExample(SchemaMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMAMETA
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SchemaMeta record, @Param("example") SchemaMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHEMAMETA
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SchemaMeta record, @Param("example") SchemaMetaExample example);
}