package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.StudyEventDefForm;
import tw.edu.ym.csis.maindb.model.StudyEventDefFormExample;

public interface StudyEventDefFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYEVENTDEFFORM
     *
     * @mbggenerated
     */
    int countByExample(StudyEventDefFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYEVENTDEFFORM
     *
     * @mbggenerated
     */
    int deleteByExample(StudyEventDefFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYEVENTDEFFORM
     *
     * @mbggenerated
     */
    int insert(StudyEventDefForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYEVENTDEFFORM
     *
     * @mbggenerated
     */
    int insertSelective(StudyEventDefForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYEVENTDEFFORM
     *
     * @mbggenerated
     */
    List<StudyEventDefForm> selectByExample(StudyEventDefFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYEVENTDEFFORM
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StudyEventDefForm record, @Param("example") StudyEventDefFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYEVENTDEFFORM
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StudyEventDefForm record, @Param("example") StudyEventDefFormExample example);
}