package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.StudyPlan;
import tw.edu.ym.csis.maindb.model.StudyPlanExample;

public interface StudyPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYPLAN
     *
     * @mbggenerated
     */
    int countByExample(StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYPLAN
     *
     * @mbggenerated
     */
    int deleteByExample(StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYPLAN
     *
     * @mbggenerated
     */
    int insert(StudyPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYPLAN
     *
     * @mbggenerated
     */
    int insertSelective(StudyPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYPLAN
     *
     * @mbggenerated
     */
    List<StudyPlan> selectByExample(StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYPLAN
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StudyPlan record, @Param("example") StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDYPLAN
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StudyPlan record, @Param("example") StudyPlanExample example);
}