package tw.edu.ym.csis.maindb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.maindb.model.Visit;
import tw.edu.ym.csis.maindb.model.VisitExample;

public interface VisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT
     *
     * @mbggenerated
     */
    int countByExample(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT
     *
     * @mbggenerated
     */
    int deleteByExample(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT
     *
     * @mbggenerated
     */
    int insert(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT
     *
     * @mbggenerated
     */
    int insertSelective(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT
     *
     * @mbggenerated
     */
    List<Visit> selectByExample(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Visit record, @Param("example") VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Visit record, @Param("example") VisitExample example);
}