package tw.edu.ym.csis.maindb.model;

import java.util.Date;

public class Attachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.FILENAME
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.DATARECORDID
     *
     * @mbggenerated
     */
    private Long datarecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.ATTACH_DT
     *
     * @mbggenerated
     */
    private Date attachDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.ID
     *
     * @return the value of ATTACHMENT.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.ID
     *
     * @param id the value for ATTACHMENT.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.NAME
     *
     * @return the value of ATTACHMENT.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.NAME
     *
     * @param name the value for ATTACHMENT.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.FILENAME
     *
     * @return the value of ATTACHMENT.FILENAME
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.FILENAME
     *
     * @param filename the value for ATTACHMENT.FILENAME
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.DATARECORDID
     *
     * @return the value of ATTACHMENT.DATARECORDID
     *
     * @mbggenerated
     */
    public Long getDatarecordid() {
        return datarecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.DATARECORDID
     *
     * @param datarecordid the value for ATTACHMENT.DATARECORDID
     *
     * @mbggenerated
     */
    public void setDatarecordid(Long datarecordid) {
        this.datarecordid = datarecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.ATTACH_DT
     *
     * @return the value of ATTACHMENT.ATTACH_DT
     *
     * @mbggenerated
     */
    public Date getAttachDt() {
        return attachDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.ATTACH_DT
     *
     * @param attachDt the value for ATTACHMENT.ATTACH_DT
     *
     * @mbggenerated
     */
    public void setAttachDt(Date attachDt) {
        this.attachDt = attachDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACHMENT.DESCRIPTION
     *
     * @return the value of ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACHMENT.DESCRIPTION
     *
     * @param description the value for ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}