package tw.edu.ym.csis.maindb.model;

public class ClobContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLOBCONTENT.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLOBCONTENT.CLOBCONTENT
     *
     * @mbggenerated
     */
    private String clobcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLOBCONTENT.ID
     *
     * @return the value of CLOBCONTENT.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLOBCONTENT.ID
     *
     * @param id the value for CLOBCONTENT.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLOBCONTENT.CLOBCONTENT
     *
     * @return the value of CLOBCONTENT.CLOBCONTENT
     *
     * @mbggenerated
     */
    public String getClobcontent() {
        return clobcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLOBCONTENT.CLOBCONTENT
     *
     * @param clobcontent the value for CLOBCONTENT.CLOBCONTENT
     *
     * @mbggenerated
     */
    public void setClobcontent(String clobcontent) {
        this.clobcontent = clobcontent == null ? null : clobcontent.trim();
    }
}