package tw.edu.ym.csis.maindb.model;

import java.util.Date;

public class Datarecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.FORMVERSIONID
     *
     * @mbggenerated
     */
    private Long formversionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.FORMGROUPID
     *
     * @mbggenerated
     */
    private Long formgroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.EXTERNALDATAID
     *
     * @mbggenerated
     */
    private Long externaldataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.EVENTID
     *
     * @mbggenerated
     */
    private Long eventid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.EVENTSEQUENCE
     *
     * @mbggenerated
     */
    private Long eventsequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.FILLEDOUTLABEL
     *
     * @mbggenerated
     */
    private String filledoutlabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.CREATORID
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.CREATEDDATE
     *
     * @mbggenerated
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.LASTUPDID
     *
     * @mbggenerated
     */
    private String lastupdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATARECORD.LASTUPDDATE
     *
     * @mbggenerated
     */
    private Date lastupddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.ID
     *
     * @return the value of DATARECORD.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.ID
     *
     * @param id the value for DATARECORD.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.FORMVERSIONID
     *
     * @return the value of DATARECORD.FORMVERSIONID
     *
     * @mbggenerated
     */
    public Long getFormversionid() {
        return formversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.FORMVERSIONID
     *
     * @param formversionid the value for DATARECORD.FORMVERSIONID
     *
     * @mbggenerated
     */
    public void setFormversionid(Long formversionid) {
        this.formversionid = formversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.FORMGROUPID
     *
     * @return the value of DATARECORD.FORMGROUPID
     *
     * @mbggenerated
     */
    public Long getFormgroupid() {
        return formgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.FORMGROUPID
     *
     * @param formgroupid the value for DATARECORD.FORMGROUPID
     *
     * @mbggenerated
     */
    public void setFormgroupid(Long formgroupid) {
        this.formgroupid = formgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.EXTERNALDATAID
     *
     * @return the value of DATARECORD.EXTERNALDATAID
     *
     * @mbggenerated
     */
    public Long getExternaldataid() {
        return externaldataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.EXTERNALDATAID
     *
     * @param externaldataid the value for DATARECORD.EXTERNALDATAID
     *
     * @mbggenerated
     */
    public void setExternaldataid(Long externaldataid) {
        this.externaldataid = externaldataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.STATUS
     *
     * @return the value of DATARECORD.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.STATUS
     *
     * @param status the value for DATARECORD.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.EVENTID
     *
     * @return the value of DATARECORD.EVENTID
     *
     * @mbggenerated
     */
    public Long getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.EVENTID
     *
     * @param eventid the value for DATARECORD.EVENTID
     *
     * @mbggenerated
     */
    public void setEventid(Long eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.EVENTSEQUENCE
     *
     * @return the value of DATARECORD.EVENTSEQUENCE
     *
     * @mbggenerated
     */
    public Long getEventsequence() {
        return eventsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.EVENTSEQUENCE
     *
     * @param eventsequence the value for DATARECORD.EVENTSEQUENCE
     *
     * @mbggenerated
     */
    public void setEventsequence(Long eventsequence) {
        this.eventsequence = eventsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.FILLEDOUTLABEL
     *
     * @return the value of DATARECORD.FILLEDOUTLABEL
     *
     * @mbggenerated
     */
    public String getFilledoutlabel() {
        return filledoutlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.FILLEDOUTLABEL
     *
     * @param filledoutlabel the value for DATARECORD.FILLEDOUTLABEL
     *
     * @mbggenerated
     */
    public void setFilledoutlabel(String filledoutlabel) {
        this.filledoutlabel = filledoutlabel == null ? null : filledoutlabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.CREATORID
     *
     * @return the value of DATARECORD.CREATORID
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.CREATORID
     *
     * @param creatorid the value for DATARECORD.CREATORID
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.CREATEDDATE
     *
     * @return the value of DATARECORD.CREATEDDATE
     *
     * @mbggenerated
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.CREATEDDATE
     *
     * @param createddate the value for DATARECORD.CREATEDDATE
     *
     * @mbggenerated
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.LASTUPDID
     *
     * @return the value of DATARECORD.LASTUPDID
     *
     * @mbggenerated
     */
    public String getLastupdid() {
        return lastupdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.LASTUPDID
     *
     * @param lastupdid the value for DATARECORD.LASTUPDID
     *
     * @mbggenerated
     */
    public void setLastupdid(String lastupdid) {
        this.lastupdid = lastupdid == null ? null : lastupdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATARECORD.LASTUPDDATE
     *
     * @return the value of DATARECORD.LASTUPDDATE
     *
     * @mbggenerated
     */
    public Date getLastupddate() {
        return lastupddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATARECORD.LASTUPDDATE
     *
     * @param lastupddate the value for DATARECORD.LASTUPDDATE
     *
     * @mbggenerated
     */
    public void setLastupddate(Date lastupddate) {
        this.lastupddate = lastupddate;
    }
}