package tw.edu.ym.csis.maindb.model;

import java.util.Date;

public class Diagnosis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.CODE_TYPE
     *
     * @mbggenerated
     */
    private String codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.DCPID
     *
     * @mbggenerated
     */
    private Long dcpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.CREATORID
     *
     * @mbggenerated
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.CREATEDDATE
     *
     * @mbggenerated
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.LASTUPDID
     *
     * @mbggenerated
     */
    private String lastupdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.LASTUPDDATE
     *
     * @mbggenerated
     */
    private Date lastupddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.PROTOCOLID
     *
     * @mbggenerated
     */
    private Long protocolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.CREATED_BY
     *
     * @mbggenerated
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIAGNOSIS.CREATION_DT
     *
     * @mbggenerated
     */
    private Date creationDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.ID
     *
     * @return the value of DIAGNOSIS.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.ID
     *
     * @param id the value for DIAGNOSIS.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.CODE_TYPE
     *
     * @return the value of DIAGNOSIS.CODE_TYPE
     *
     * @mbggenerated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.CODE_TYPE
     *
     * @param codeType the value for DIAGNOSIS.CODE_TYPE
     *
     * @mbggenerated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.CODE
     *
     * @return the value of DIAGNOSIS.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.CODE
     *
     * @param code the value for DIAGNOSIS.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.NAME
     *
     * @return the value of DIAGNOSIS.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.NAME
     *
     * @param name the value for DIAGNOSIS.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.DESCRIPTION
     *
     * @return the value of DIAGNOSIS.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.DESCRIPTION
     *
     * @param description the value for DIAGNOSIS.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.DCPID
     *
     * @return the value of DIAGNOSIS.DCPID
     *
     * @mbggenerated
     */
    public Long getDcpid() {
        return dcpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.DCPID
     *
     * @param dcpid the value for DIAGNOSIS.DCPID
     *
     * @mbggenerated
     */
    public void setDcpid(Long dcpid) {
        this.dcpid = dcpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.CREATORID
     *
     * @return the value of DIAGNOSIS.CREATORID
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.CREATORID
     *
     * @param creatorid the value for DIAGNOSIS.CREATORID
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.CREATEDDATE
     *
     * @return the value of DIAGNOSIS.CREATEDDATE
     *
     * @mbggenerated
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.CREATEDDATE
     *
     * @param createddate the value for DIAGNOSIS.CREATEDDATE
     *
     * @mbggenerated
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.LASTUPDID
     *
     * @return the value of DIAGNOSIS.LASTUPDID
     *
     * @mbggenerated
     */
    public String getLastupdid() {
        return lastupdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.LASTUPDID
     *
     * @param lastupdid the value for DIAGNOSIS.LASTUPDID
     *
     * @mbggenerated
     */
    public void setLastupdid(String lastupdid) {
        this.lastupdid = lastupdid == null ? null : lastupdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.LASTUPDDATE
     *
     * @return the value of DIAGNOSIS.LASTUPDDATE
     *
     * @mbggenerated
     */
    public Date getLastupddate() {
        return lastupddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.LASTUPDDATE
     *
     * @param lastupddate the value for DIAGNOSIS.LASTUPDDATE
     *
     * @mbggenerated
     */
    public void setLastupddate(Date lastupddate) {
        this.lastupddate = lastupddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.PROTOCOLID
     *
     * @return the value of DIAGNOSIS.PROTOCOLID
     *
     * @mbggenerated
     */
    public Long getProtocolid() {
        return protocolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.PROTOCOLID
     *
     * @param protocolid the value for DIAGNOSIS.PROTOCOLID
     *
     * @mbggenerated
     */
    public void setProtocolid(Long protocolid) {
        this.protocolid = protocolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.CREATED_BY
     *
     * @return the value of DIAGNOSIS.CREATED_BY
     *
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.CREATED_BY
     *
     * @param createdBy the value for DIAGNOSIS.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIAGNOSIS.CREATION_DT
     *
     * @return the value of DIAGNOSIS.CREATION_DT
     *
     * @mbggenerated
     */
    public Date getCreationDt() {
        return creationDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIAGNOSIS.CREATION_DT
     *
     * @param creationDt the value for DIAGNOSIS.CREATION_DT
     *
     * @mbggenerated
     */
    public void setCreationDt(Date creationDt) {
        this.creationDt = creationDt;
    }
}