package tw.edu.ym.csis.maindb.model;

import java.math.BigDecimal;
import java.util.Date;

public class EventHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT_HISTORY.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT_HISTORY.OBJECT_TYPE
     *
     * @mbggenerated
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT_HISTORY.OBJECT_ID
     *
     * @mbggenerated
     */
    private BigDecimal objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT_HISTORY.EVENT_ID
     *
     * @mbggenerated
     */
    private Long eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT_HISTORY.PERSON_ID
     *
     * @mbggenerated
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT_HISTORY.EVENT_DATE
     *
     * @mbggenerated
     */
    private Date eventDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT_HISTORY.INFO_1
     *
     * @mbggenerated
     */
    private String info1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT_HISTORY.INFO_2
     *
     * @mbggenerated
     */
    private String info2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT_HISTORY.ID
     *
     * @return the value of EVENT_HISTORY.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT_HISTORY.ID
     *
     * @param id the value for EVENT_HISTORY.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT_HISTORY.OBJECT_TYPE
     *
     * @return the value of EVENT_HISTORY.OBJECT_TYPE
     *
     * @mbggenerated
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT_HISTORY.OBJECT_TYPE
     *
     * @param objectType the value for EVENT_HISTORY.OBJECT_TYPE
     *
     * @mbggenerated
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT_HISTORY.OBJECT_ID
     *
     * @return the value of EVENT_HISTORY.OBJECT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT_HISTORY.OBJECT_ID
     *
     * @param objectId the value for EVENT_HISTORY.OBJECT_ID
     *
     * @mbggenerated
     */
    public void setObjectId(BigDecimal objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT_HISTORY.EVENT_ID
     *
     * @return the value of EVENT_HISTORY.EVENT_ID
     *
     * @mbggenerated
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT_HISTORY.EVENT_ID
     *
     * @param eventId the value for EVENT_HISTORY.EVENT_ID
     *
     * @mbggenerated
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT_HISTORY.PERSON_ID
     *
     * @return the value of EVENT_HISTORY.PERSON_ID
     *
     * @mbggenerated
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT_HISTORY.PERSON_ID
     *
     * @param personId the value for EVENT_HISTORY.PERSON_ID
     *
     * @mbggenerated
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT_HISTORY.EVENT_DATE
     *
     * @return the value of EVENT_HISTORY.EVENT_DATE
     *
     * @mbggenerated
     */
    public Date getEventDate() {
        return eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT_HISTORY.EVENT_DATE
     *
     * @param eventDate the value for EVENT_HISTORY.EVENT_DATE
     *
     * @mbggenerated
     */
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT_HISTORY.INFO_1
     *
     * @return the value of EVENT_HISTORY.INFO_1
     *
     * @mbggenerated
     */
    public String getInfo1() {
        return info1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT_HISTORY.INFO_1
     *
     * @param info1 the value for EVENT_HISTORY.INFO_1
     *
     * @mbggenerated
     */
    public void setInfo1(String info1) {
        this.info1 = info1 == null ? null : info1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT_HISTORY.INFO_2
     *
     * @return the value of EVENT_HISTORY.INFO_2
     *
     * @mbggenerated
     */
    public String getInfo2() {
        return info2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT_HISTORY.INFO_2
     *
     * @param info2 the value for EVENT_HISTORY.INFO_2
     *
     * @mbggenerated
     */
    public void setInfo2(String info2) {
        this.info2 = info2 == null ? null : info2.trim();
    }
}