package tw.edu.ym.csis.maindb.model;

public class FormImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FORMIMAGES.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FORMIMAGES.PROTOCOLID
     *
     * @mbggenerated
     */
    private Long protocolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FORMIMAGES.IMAGE_DESC
     *
     * @mbggenerated
     */
    private String imageDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FORMIMAGES.IMAGE
     *
     * @mbggenerated
     */
    private byte[] image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FORMIMAGES.ID
     *
     * @return the value of FORMIMAGES.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FORMIMAGES.ID
     *
     * @param id the value for FORMIMAGES.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FORMIMAGES.PROTOCOLID
     *
     * @return the value of FORMIMAGES.PROTOCOLID
     *
     * @mbggenerated
     */
    public Long getProtocolid() {
        return protocolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FORMIMAGES.PROTOCOLID
     *
     * @param protocolid the value for FORMIMAGES.PROTOCOLID
     *
     * @mbggenerated
     */
    public void setProtocolid(Long protocolid) {
        this.protocolid = protocolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FORMIMAGES.IMAGE_DESC
     *
     * @return the value of FORMIMAGES.IMAGE_DESC
     *
     * @mbggenerated
     */
    public String getImageDesc() {
        return imageDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FORMIMAGES.IMAGE_DESC
     *
     * @param imageDesc the value for FORMIMAGES.IMAGE_DESC
     *
     * @mbggenerated
     */
    public void setImageDesc(String imageDesc) {
        this.imageDesc = imageDesc == null ? null : imageDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FORMIMAGES.IMAGE
     *
     * @return the value of FORMIMAGES.IMAGE
     *
     * @mbggenerated
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FORMIMAGES.IMAGE
     *
     * @param image the value for FORMIMAGES.IMAGE
     *
     * @mbggenerated
     */
    public void setImage(byte[] image) {
        this.image = image;
    }
}