package tw.edu.ym.csis.maindb.model;

import java.math.BigDecimal;

public class ImageData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGEDATA.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGEDATA.DATARECORDID
     *
     * @mbggenerated
     */
    private BigDecimal datarecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGEDATA.XPOS
     *
     * @mbggenerated
     */
    private BigDecimal xpos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGEDATA.YPOS
     *
     * @mbggenerated
     */
    private BigDecimal ypos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGEDATA.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGEDATA.ID
     *
     * @return the value of IMAGEDATA.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGEDATA.ID
     *
     * @param id the value for IMAGEDATA.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGEDATA.DATARECORDID
     *
     * @return the value of IMAGEDATA.DATARECORDID
     *
     * @mbggenerated
     */
    public BigDecimal getDatarecordid() {
        return datarecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGEDATA.DATARECORDID
     *
     * @param datarecordid the value for IMAGEDATA.DATARECORDID
     *
     * @mbggenerated
     */
    public void setDatarecordid(BigDecimal datarecordid) {
        this.datarecordid = datarecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGEDATA.XPOS
     *
     * @return the value of IMAGEDATA.XPOS
     *
     * @mbggenerated
     */
    public BigDecimal getXpos() {
        return xpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGEDATA.XPOS
     *
     * @param xpos the value for IMAGEDATA.XPOS
     *
     * @mbggenerated
     */
    public void setXpos(BigDecimal xpos) {
        this.xpos = xpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGEDATA.YPOS
     *
     * @return the value of IMAGEDATA.YPOS
     *
     * @mbggenerated
     */
    public BigDecimal getYpos() {
        return ypos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGEDATA.YPOS
     *
     * @param ypos the value for IMAGEDATA.YPOS
     *
     * @mbggenerated
     */
    public void setYpos(BigDecimal ypos) {
        this.ypos = ypos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGEDATA.TYPE
     *
     * @return the value of IMAGEDATA.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGEDATA.TYPE
     *
     * @param type the value for IMAGEDATA.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}