package tw.edu.ym.csis.maindb.model;

public class LogicalExpression {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGICALEXPRESSION.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGICALEXPRESSION.SAVEDQUERYID
     *
     * @mbggenerated
     */
    private Long savedqueryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGICALEXPRESSION.LOGOPERATORCODE
     *
     * @mbggenerated
     */
    private String logoperatorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGICALEXPRESSION.PARENTLOGEXPRESSIONID
     *
     * @mbggenerated
     */
    private Long parentlogexpressionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGICALEXPRESSION.TOP_FLG
     *
     * @mbggenerated
     */
    private String topFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGICALEXPRESSION.LOGEXPRESSIONNAME
     *
     * @mbggenerated
     */
    private String logexpressionname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGICALEXPRESSION.ID
     *
     * @return the value of LOGICALEXPRESSION.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGICALEXPRESSION.ID
     *
     * @param id the value for LOGICALEXPRESSION.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGICALEXPRESSION.SAVEDQUERYID
     *
     * @return the value of LOGICALEXPRESSION.SAVEDQUERYID
     *
     * @mbggenerated
     */
    public Long getSavedqueryid() {
        return savedqueryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGICALEXPRESSION.SAVEDQUERYID
     *
     * @param savedqueryid the value for LOGICALEXPRESSION.SAVEDQUERYID
     *
     * @mbggenerated
     */
    public void setSavedqueryid(Long savedqueryid) {
        this.savedqueryid = savedqueryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGICALEXPRESSION.LOGOPERATORCODE
     *
     * @return the value of LOGICALEXPRESSION.LOGOPERATORCODE
     *
     * @mbggenerated
     */
    public String getLogoperatorcode() {
        return logoperatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGICALEXPRESSION.LOGOPERATORCODE
     *
     * @param logoperatorcode the value for LOGICALEXPRESSION.LOGOPERATORCODE
     *
     * @mbggenerated
     */
    public void setLogoperatorcode(String logoperatorcode) {
        this.logoperatorcode = logoperatorcode == null ? null : logoperatorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGICALEXPRESSION.PARENTLOGEXPRESSIONID
     *
     * @return the value of LOGICALEXPRESSION.PARENTLOGEXPRESSIONID
     *
     * @mbggenerated
     */
    public Long getParentlogexpressionid() {
        return parentlogexpressionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGICALEXPRESSION.PARENTLOGEXPRESSIONID
     *
     * @param parentlogexpressionid the value for LOGICALEXPRESSION.PARENTLOGEXPRESSIONID
     *
     * @mbggenerated
     */
    public void setParentlogexpressionid(Long parentlogexpressionid) {
        this.parentlogexpressionid = parentlogexpressionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGICALEXPRESSION.TOP_FLG
     *
     * @return the value of LOGICALEXPRESSION.TOP_FLG
     *
     * @mbggenerated
     */
    public String getTopFlg() {
        return topFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGICALEXPRESSION.TOP_FLG
     *
     * @param topFlg the value for LOGICALEXPRESSION.TOP_FLG
     *
     * @mbggenerated
     */
    public void setTopFlg(String topFlg) {
        this.topFlg = topFlg == null ? null : topFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGICALEXPRESSION.LOGEXPRESSIONNAME
     *
     * @return the value of LOGICALEXPRESSION.LOGEXPRESSIONNAME
     *
     * @mbggenerated
     */
    public String getLogexpressionname() {
        return logexpressionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGICALEXPRESSION.LOGEXPRESSIONNAME
     *
     * @param logexpressionname the value for LOGICALEXPRESSION.LOGEXPRESSIONNAME
     *
     * @mbggenerated
     */
    public void setLogexpressionname(String logexpressionname) {
        this.logexpressionname = logexpressionname == null ? null : logexpressionname.trim();
    }
}