package tw.edu.ym.csis.maindb.model;

public class LogicalOperator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGICALOPERATOR.OPERATORCODE
     *
     * @mbggenerated
     */
    private String operatorcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGICALOPERATOR.OPERATORCODE
     *
     * @return the value of LOGICALOPERATOR.OPERATORCODE
     *
     * @mbggenerated
     */
    public String getOperatorcode() {
        return operatorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGICALOPERATOR.OPERATORCODE
     *
     * @param operatorcode the value for LOGICALOPERATOR.OPERATORCODE
     *
     * @mbggenerated
     */
    public void setOperatorcode(String operatorcode) {
        this.operatorcode = operatorcode == null ? null : operatorcode.trim();
    }
}