package tw.edu.ym.csis.maindb.model;

import java.util.Date;

public class Patient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.PATIENTID
     *
     * @mbggenerated
     */
    private Long patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.MRN
     *
     * @mbggenerated
     */
    private String mrn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.LAST_NAME
     *
     * @mbggenerated
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.FIRST_NAME
     *
     * @mbggenerated
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.GENDER
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.DOB
     *
     * @mbggenerated
     */
    private Date dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.ETHNICITY
     *
     * @mbggenerated
     */
    private String ethnicity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.RACE
     *
     * @mbggenerated
     */
    private String race;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.STREET_ADDRESS_1
     *
     * @mbggenerated
     */
    private String streetAddress1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.STREET_ADDRESS_2
     *
     * @mbggenerated
     */
    private String streetAddress2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.STATE_CD
     *
     * @mbggenerated
     */
    private String stateCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.ZIP
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.ALT_PHONE
     *
     * @mbggenerated
     */
    private String altPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.SALUTATION
     *
     * @mbggenerated
     */
    private String salutation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.COUNTRY
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.AUTHKEY
     *
     * @mbggenerated
     */
    private String authkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.SYSTEMACCESS
     *
     * @mbggenerated
     */
    private String systemaccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.HANDNESS
     *
     * @mbggenerated
     */
    private Short handness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.OCCUPATION
     *
     * @mbggenerated
     */
    private String occupation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.PATIENTID
     *
     * @return the value of PATIENT.PATIENTID
     *
     * @mbggenerated
     */
    public Long getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.PATIENTID
     *
     * @param patientid the value for PATIENT.PATIENTID
     *
     * @mbggenerated
     */
    public void setPatientid(Long patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.MRN
     *
     * @return the value of PATIENT.MRN
     *
     * @mbggenerated
     */
    public String getMrn() {
        return mrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.MRN
     *
     * @param mrn the value for PATIENT.MRN
     *
     * @mbggenerated
     */
    public void setMrn(String mrn) {
        this.mrn = mrn == null ? null : mrn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.LAST_NAME
     *
     * @return the value of PATIENT.LAST_NAME
     *
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.LAST_NAME
     *
     * @param lastName the value for PATIENT.LAST_NAME
     *
     * @mbggenerated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.FIRST_NAME
     *
     * @return the value of PATIENT.FIRST_NAME
     *
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.FIRST_NAME
     *
     * @param firstName the value for PATIENT.FIRST_NAME
     *
     * @mbggenerated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.PHONE
     *
     * @return the value of PATIENT.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.PHONE
     *
     * @param phone the value for PATIENT.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.GENDER
     *
     * @return the value of PATIENT.GENDER
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.GENDER
     *
     * @param gender the value for PATIENT.GENDER
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.DOB
     *
     * @return the value of PATIENT.DOB
     *
     * @mbggenerated
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.DOB
     *
     * @param dob the value for PATIENT.DOB
     *
     * @mbggenerated
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.ETHNICITY
     *
     * @return the value of PATIENT.ETHNICITY
     *
     * @mbggenerated
     */
    public String getEthnicity() {
        return ethnicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.ETHNICITY
     *
     * @param ethnicity the value for PATIENT.ETHNICITY
     *
     * @mbggenerated
     */
    public void setEthnicity(String ethnicity) {
        this.ethnicity = ethnicity == null ? null : ethnicity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.RACE
     *
     * @return the value of PATIENT.RACE
     *
     * @mbggenerated
     */
    public String getRace() {
        return race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.RACE
     *
     * @param race the value for PATIENT.RACE
     *
     * @mbggenerated
     */
    public void setRace(String race) {
        this.race = race == null ? null : race.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.STREET_ADDRESS_1
     *
     * @return the value of PATIENT.STREET_ADDRESS_1
     *
     * @mbggenerated
     */
    public String getStreetAddress1() {
        return streetAddress1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.STREET_ADDRESS_1
     *
     * @param streetAddress1 the value for PATIENT.STREET_ADDRESS_1
     *
     * @mbggenerated
     */
    public void setStreetAddress1(String streetAddress1) {
        this.streetAddress1 = streetAddress1 == null ? null : streetAddress1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.STREET_ADDRESS_2
     *
     * @return the value of PATIENT.STREET_ADDRESS_2
     *
     * @mbggenerated
     */
    public String getStreetAddress2() {
        return streetAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.STREET_ADDRESS_2
     *
     * @param streetAddress2 the value for PATIENT.STREET_ADDRESS_2
     *
     * @mbggenerated
     */
    public void setStreetAddress2(String streetAddress2) {
        this.streetAddress2 = streetAddress2 == null ? null : streetAddress2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.CITY
     *
     * @return the value of PATIENT.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.CITY
     *
     * @param city the value for PATIENT.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.STATE_CD
     *
     * @return the value of PATIENT.STATE_CD
     *
     * @mbggenerated
     */
    public String getStateCd() {
        return stateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.STATE_CD
     *
     * @param stateCd the value for PATIENT.STATE_CD
     *
     * @mbggenerated
     */
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd == null ? null : stateCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.ZIP
     *
     * @return the value of PATIENT.ZIP
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.ZIP
     *
     * @param zip the value for PATIENT.ZIP
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.ALT_PHONE
     *
     * @return the value of PATIENT.ALT_PHONE
     *
     * @mbggenerated
     */
    public String getAltPhone() {
        return altPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.ALT_PHONE
     *
     * @param altPhone the value for PATIENT.ALT_PHONE
     *
     * @mbggenerated
     */
    public void setAltPhone(String altPhone) {
        this.altPhone = altPhone == null ? null : altPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.SALUTATION
     *
     * @return the value of PATIENT.SALUTATION
     *
     * @mbggenerated
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.SALUTATION
     *
     * @param salutation the value for PATIENT.SALUTATION
     *
     * @mbggenerated
     */
    public void setSalutation(String salutation) {
        this.salutation = salutation == null ? null : salutation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.COUNTRY
     *
     * @return the value of PATIENT.COUNTRY
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.COUNTRY
     *
     * @param country the value for PATIENT.COUNTRY
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.NOTE
     *
     * @return the value of PATIENT.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.NOTE
     *
     * @param note the value for PATIENT.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.AUTHKEY
     *
     * @return the value of PATIENT.AUTHKEY
     *
     * @mbggenerated
     */
    public String getAuthkey() {
        return authkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.AUTHKEY
     *
     * @param authkey the value for PATIENT.AUTHKEY
     *
     * @mbggenerated
     */
    public void setAuthkey(String authkey) {
        this.authkey = authkey == null ? null : authkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.USERNAME
     *
     * @return the value of PATIENT.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.USERNAME
     *
     * @param username the value for PATIENT.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.SYSTEMACCESS
     *
     * @return the value of PATIENT.SYSTEMACCESS
     *
     * @mbggenerated
     */
    public String getSystemaccess() {
        return systemaccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.SYSTEMACCESS
     *
     * @param systemaccess the value for PATIENT.SYSTEMACCESS
     *
     * @mbggenerated
     */
    public void setSystemaccess(String systemaccess) {
        this.systemaccess = systemaccess == null ? null : systemaccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.HANDNESS
     *
     * @return the value of PATIENT.HANDNESS
     *
     * @mbggenerated
     */
    public Short getHandness() {
        return handness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.HANDNESS
     *
     * @param handness the value for PATIENT.HANDNESS
     *
     * @mbggenerated
     */
    public void setHandness(Short handness) {
        this.handness = handness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.OCCUPATION
     *
     * @return the value of PATIENT.OCCUPATION
     *
     * @mbggenerated
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.OCCUPATION
     *
     * @param occupation the value for PATIENT.OCCUPATION
     *
     * @mbggenerated
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }
}