package tw.edu.ym.csis.maindb.model;

public class PclRecruitment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCLRECRUITMENT.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCLRECRUITMENT.PROTOCOLID
     *
     * @mbggenerated
     */
    private Long protocolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCLRECRUITMENT.RECRUITMENTID
     *
     * @mbggenerated
     */
    private Long recruitmentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCLRECRUITMENT.ID
     *
     * @return the value of PCLRECRUITMENT.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCLRECRUITMENT.ID
     *
     * @param id the value for PCLRECRUITMENT.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCLRECRUITMENT.PROTOCOLID
     *
     * @return the value of PCLRECRUITMENT.PROTOCOLID
     *
     * @mbggenerated
     */
    public Long getProtocolid() {
        return protocolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCLRECRUITMENT.PROTOCOLID
     *
     * @param protocolid the value for PCLRECRUITMENT.PROTOCOLID
     *
     * @mbggenerated
     */
    public void setProtocolid(Long protocolid) {
        this.protocolid = protocolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCLRECRUITMENT.RECRUITMENTID
     *
     * @return the value of PCLRECRUITMENT.RECRUITMENTID
     *
     * @mbggenerated
     */
    public Long getRecruitmentid() {
        return recruitmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCLRECRUITMENT.RECRUITMENTID
     *
     * @param recruitmentid the value for PCLRECRUITMENT.RECRUITMENTID
     *
     * @mbggenerated
     */
    public void setRecruitmentid(Long recruitmentid) {
        this.recruitmentid = recruitmentid;
    }
}