package tw.edu.ym.csis.maindb.model;

public class PublicSitePatient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLICSITEPATIENT.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLICSITEPATIENT.PUBLICSITEID
     *
     * @mbggenerated
     */
    private Integer publicsiteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLICSITEPATIENT.PATIENTID
     *
     * @mbggenerated
     */
    private Integer patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLICSITEPATIENT.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLICSITEPATIENT.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLICSITEPATIENT.ID
     *
     * @return the value of PUBLICSITEPATIENT.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLICSITEPATIENT.ID
     *
     * @param id the value for PUBLICSITEPATIENT.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLICSITEPATIENT.PUBLICSITEID
     *
     * @return the value of PUBLICSITEPATIENT.PUBLICSITEID
     *
     * @mbggenerated
     */
    public Integer getPublicsiteid() {
        return publicsiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLICSITEPATIENT.PUBLICSITEID
     *
     * @param publicsiteid the value for PUBLICSITEPATIENT.PUBLICSITEID
     *
     * @mbggenerated
     */
    public void setPublicsiteid(Integer publicsiteid) {
        this.publicsiteid = publicsiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLICSITEPATIENT.PATIENTID
     *
     * @return the value of PUBLICSITEPATIENT.PATIENTID
     *
     * @mbggenerated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLICSITEPATIENT.PATIENTID
     *
     * @param patientid the value for PUBLICSITEPATIENT.PATIENTID
     *
     * @mbggenerated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLICSITEPATIENT.USERNAME
     *
     * @return the value of PUBLICSITEPATIENT.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLICSITEPATIENT.USERNAME
     *
     * @param username the value for PUBLICSITEPATIENT.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLICSITEPATIENT.PASSWORD
     *
     * @return the value of PUBLICSITEPATIENT.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLICSITEPATIENT.PASSWORD
     *
     * @param password the value for PUBLICSITEPATIENT.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}