package tw.edu.ym.csis.maindb.model;

import java.util.Date;

public class QueryHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUERYHISTORY.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUERYHISTORY.QUERYNAME
     *
     * @mbggenerated
     */
    private String queryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUERYHISTORY.USERID
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUERYHISTORY.CREATEDATE
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUERYHISTORY.MODULE
     *
     * @mbggenerated
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUERYHISTORY.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUERYHISTORY.QUERYCONTENT
     *
     * @mbggenerated
     */
    private byte[] querycontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUERYHISTORY.ID
     *
     * @return the value of QUERYHISTORY.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUERYHISTORY.ID
     *
     * @param id the value for QUERYHISTORY.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUERYHISTORY.QUERYNAME
     *
     * @return the value of QUERYHISTORY.QUERYNAME
     *
     * @mbggenerated
     */
    public String getQueryname() {
        return queryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUERYHISTORY.QUERYNAME
     *
     * @param queryname the value for QUERYHISTORY.QUERYNAME
     *
     * @mbggenerated
     */
    public void setQueryname(String queryname) {
        this.queryname = queryname == null ? null : queryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUERYHISTORY.USERID
     *
     * @return the value of QUERYHISTORY.USERID
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUERYHISTORY.USERID
     *
     * @param userid the value for QUERYHISTORY.USERID
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUERYHISTORY.CREATEDATE
     *
     * @return the value of QUERYHISTORY.CREATEDATE
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUERYHISTORY.CREATEDATE
     *
     * @param createdate the value for QUERYHISTORY.CREATEDATE
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUERYHISTORY.MODULE
     *
     * @return the value of QUERYHISTORY.MODULE
     *
     * @mbggenerated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUERYHISTORY.MODULE
     *
     * @param module the value for QUERYHISTORY.MODULE
     *
     * @mbggenerated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUERYHISTORY.DESCRIPTION
     *
     * @return the value of QUERYHISTORY.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUERYHISTORY.DESCRIPTION
     *
     * @param description the value for QUERYHISTORY.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUERYHISTORY.QUERYCONTENT
     *
     * @return the value of QUERYHISTORY.QUERYCONTENT
     *
     * @mbggenerated
     */
    public byte[] getQuerycontent() {
        return querycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUERYHISTORY.QUERYCONTENT
     *
     * @param querycontent the value for QUERYHISTORY.QUERYCONTENT
     *
     * @mbggenerated
     */
    public void setQuerycontent(byte[] querycontent) {
        this.querycontent = querycontent;
    }
}