package tw.edu.ym.csis.maindb.model;

import java.math.BigDecimal;

public class ReeportDps {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_DPS.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_DPS.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_DPS.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT_DPS.PROTOCOL_ID
     *
     * @mbggenerated
     */
    private BigDecimal protocolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_DPS.ID
     *
     * @return the value of REPORT_DPS.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_DPS.ID
     *
     * @param id the value for REPORT_DPS.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_DPS.NAME
     *
     * @return the value of REPORT_DPS.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_DPS.NAME
     *
     * @param name the value for REPORT_DPS.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_DPS.CONTENT
     *
     * @return the value of REPORT_DPS.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_DPS.CONTENT
     *
     * @param content the value for REPORT_DPS.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT_DPS.PROTOCOL_ID
     *
     * @return the value of REPORT_DPS.PROTOCOL_ID
     *
     * @mbggenerated
     */
    public BigDecimal getProtocolId() {
        return protocolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT_DPS.PROTOCOL_ID
     *
     * @param protocolId the value for REPORT_DPS.PROTOCOL_ID
     *
     * @mbggenerated
     */
    public void setProtocolId(BigDecimal protocolId) {
        this.protocolId = protocolId;
    }
}