package tw.edu.ym.csis.maindb.model;

import java.util.Date;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.REPORTTEMPLATEID
     *
     * @mbggenerated
     */
    private Long reporttemplateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.CREATION_DT
     *
     * @mbggenerated
     */
    private Date creationDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.CREATED_BY
     *
     * @mbggenerated
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPORT.PATHNAME
     *
     * @mbggenerated
     */
    private String pathname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.ID
     *
     * @return the value of REPORT.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.ID
     *
     * @param id the value for REPORT.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.REPORTTEMPLATEID
     *
     * @return the value of REPORT.REPORTTEMPLATEID
     *
     * @mbggenerated
     */
    public Long getReporttemplateid() {
        return reporttemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.REPORTTEMPLATEID
     *
     * @param reporttemplateid the value for REPORT.REPORTTEMPLATEID
     *
     * @mbggenerated
     */
    public void setReporttemplateid(Long reporttemplateid) {
        this.reporttemplateid = reporttemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.NAME
     *
     * @return the value of REPORT.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.NAME
     *
     * @param name the value for REPORT.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.CREATION_DT
     *
     * @return the value of REPORT.CREATION_DT
     *
     * @mbggenerated
     */
    public Date getCreationDt() {
        return creationDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.CREATION_DT
     *
     * @param creationDt the value for REPORT.CREATION_DT
     *
     * @mbggenerated
     */
    public void setCreationDt(Date creationDt) {
        this.creationDt = creationDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.CREATED_BY
     *
     * @return the value of REPORT.CREATED_BY
     *
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.CREATED_BY
     *
     * @param createdBy the value for REPORT.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPORT.PATHNAME
     *
     * @return the value of REPORT.PATHNAME
     *
     * @mbggenerated
     */
    public String getPathname() {
        return pathname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPORT.PATHNAME
     *
     * @param pathname the value for REPORT.PATHNAME
     *
     * @mbggenerated
     */
    public void setPathname(String pathname) {
        this.pathname = pathname == null ? null : pathname.trim();
    }
}