package tw.edu.ym.csis.maindb.model;

public class SavedQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAVEDQUERY.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAVEDQUERY.DCPID
     *
     * @mbggenerated
     */
    private Long dcpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAVEDQUERY.OWNERID
     *
     * @mbggenerated
     */
    private Long ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SAVEDQUERY.QUERYNAME
     *
     * @mbggenerated
     */
    private String queryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAVEDQUERY.ID
     *
     * @return the value of SAVEDQUERY.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAVEDQUERY.ID
     *
     * @param id the value for SAVEDQUERY.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAVEDQUERY.DCPID
     *
     * @return the value of SAVEDQUERY.DCPID
     *
     * @mbggenerated
     */
    public Long getDcpid() {
        return dcpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAVEDQUERY.DCPID
     *
     * @param dcpid the value for SAVEDQUERY.DCPID
     *
     * @mbggenerated
     */
    public void setDcpid(Long dcpid) {
        this.dcpid = dcpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAVEDQUERY.OWNERID
     *
     * @return the value of SAVEDQUERY.OWNERID
     *
     * @mbggenerated
     */
    public Long getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAVEDQUERY.OWNERID
     *
     * @param ownerid the value for SAVEDQUERY.OWNERID
     *
     * @mbggenerated
     */
    public void setOwnerid(Long ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SAVEDQUERY.QUERYNAME
     *
     * @return the value of SAVEDQUERY.QUERYNAME
     *
     * @mbggenerated
     */
    public String getQueryname() {
        return queryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SAVEDQUERY.QUERYNAME
     *
     * @param queryname the value for SAVEDQUERY.QUERYNAME
     *
     * @mbggenerated
     */
    public void setQueryname(String queryname) {
        this.queryname = queryname == null ? null : queryname.trim();
    }
}