package tw.edu.ym.csis.maindb.model;

public class SchemaMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMAMETA.SCHEMAVERSION
     *
     * @mbggenerated
     */
    private String schemaversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMAMETA.METAVERSION
     *
     * @mbggenerated
     */
    private String metaversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMAMETA.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMAMETA.SCHEMAVERSION
     *
     * @return the value of SCHEMAMETA.SCHEMAVERSION
     *
     * @mbggenerated
     */
    public String getSchemaversion() {
        return schemaversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMAMETA.SCHEMAVERSION
     *
     * @param schemaversion the value for SCHEMAMETA.SCHEMAVERSION
     *
     * @mbggenerated
     */
    public void setSchemaversion(String schemaversion) {
        this.schemaversion = schemaversion == null ? null : schemaversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMAMETA.METAVERSION
     *
     * @return the value of SCHEMAMETA.METAVERSION
     *
     * @mbggenerated
     */
    public String getMetaversion() {
        return metaversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMAMETA.METAVERSION
     *
     * @param metaversion the value for SCHEMAMETA.METAVERSION
     *
     * @mbggenerated
     */
    public void setMetaversion(String metaversion) {
        this.metaversion = metaversion == null ? null : metaversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMAMETA.DESCRIPTION
     *
     * @return the value of SCHEMAMETA.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMAMETA.DESCRIPTION
     *
     * @param description the value for SCHEMAMETA.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}