package tw.edu.ym.csis.metadb.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.metadb.model.Element;
import tw.edu.ym.csis.metadb.model.ElementExample;

public interface ElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT
     *
     * @mbggenerated
     */
    int countByExample(ElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT
     *
     * @mbggenerated
     */
    int deleteByExample(ElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT
     *
     * @mbggenerated
     */
    int insert(Element record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT
     *
     * @mbggenerated
     */
    int insertSelective(Element record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT
     *
     * @mbggenerated
     */
    List<Element> selectByExample(ElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Element record, @Param("example") ElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Element record, @Param("example") ElementExample example);
}