package tw.edu.ym.csis.metadb.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import tw.edu.ym.csis.metadb.model.SkippingRule;
import tw.edu.ym.csis.metadb.model.SkippingRuleExample;

public interface SkippingRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int countByExample(SkippingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int deleteByExample(SkippingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int insert(SkippingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int insertSelective(SkippingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    List<SkippingRule> selectByExample(SkippingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    SkippingRule selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SkippingRule record, @Param("example") SkippingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SkippingRule record, @Param("example") SkippingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SkippingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKIPPINGRULE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SkippingRule record);
}